cartesian_controllers:
  - name: "Keyboard-PSM2_PeterFrancis"
    input:
        type: "increment"
        topic: "/keyboard/twist"
        jaw:
            input_topic: "/keyboard/joint_state"
            scale: 1
            idx: 14 
    output:
        control_interfaces:
            - control_topic: "/PSM2/servo_jp"
              feedback_topic: "/PSM2/measured_js"
        is_debug_output_tf: True
    kinematics:
        robot: "custom"
        module_name: "dvrk_ctr_teleop.RPR_kinematics.RPR_fetal_tool_kinematics_solver"
        class_name: "Arion_Law_tool_Kinematics_Solver"
        config: "../config/mapping/psm2_tool_rpr_sim.yaml"
clutch_topic: "/console/clutch"
