cartesian_controllers:
  - name: "Keyboard-PSM2_PeterFrancis"
    input:
        type: "increment"
        topic: "/keyboard/twist"
        jaw:
            input_topic: "/keyboard/joint_state"
            scale: 1
    output:
        control_topic: "/PSM2/servo_jp"
        extra_control_topic: "/PSM2/jaw/servo_jp"
        feedback_topic: "/PSM2/measured_js"
        extra_feedback_topic: "/PSM2/jaw/measured_js"
        is_debug_output_tf: True
    kinematics:
        robot: "fetal"
        tool:
            type:
clutch_topic: "/console/clutch"
