cartesian_controllers:
  - name: "MTML-PSM1-PeterFrancis"
    input:
        position_scale: 0.5
        type: "follow"
        topic: "/MTML/measured_cp"
        input_device_name: "/MTML/"
        jaw:
            input_topic: "/MTML/gripper/measured_js"
            scale: 1
            idx: 4
        hz_divisor: 4
        is_input_device_hold_home_off: True
        input_tf_appended_rotation:
            quaternion:
                x: 0
                y: 0
                z: 0.7071068
                w: 0.7071068
    output:
        control_interfaces:
            - control_topic: "/PSM1/servo_jp"
              feedback_topic: "/PSM1/measured_js"
            - control_topic: "/PSM1/jaw/servo_jp"
              feedback_topic: "/PSM1/jaw/measured_js"
        is_debug_output_tf: True
    kinematics:
        robot: "custom"
        module_name: "dvrk_ctr_teleop.kinematics.fetal_tool_kinematics_solver"
        class_name: "PeterFrancisToolKinematicsSolver"
clutch_topic: "/console/clutch"
switcher:
  switch_topic: "/console/operator_present"
  disable_list: []
  enable_list: ["MTML-PSM1-PeterFrancis"]
enable_at_start: []
