cartesian_controllers:
  - name: "MTML-PSM1-PeterFrancis"
    input:
        position_scale: 0.5
        type: "follow"
        topic: "/MTML/measured_cp"
        # input_2_input_reference_rot:
        #     quaternion:
        #         x: 0.9659258 #0
        #         y: 0
        #         z: 0
        #         w: -0.258819 #1
        jaw:
            input_topic: "/MTML/gripper/measured_js"
            scale: 1
            idx: 11
        hz_divisor: 5
        is_input_device_hold_home_off: True
        servo_cp_topic: "/MTML/servo_cp"
        servo_cf_topic: "/MTML/body/servo_cf"
        input_tf_appended_rotation:
            quaternion:
                x: 0
                y: 0
                z: 0.7071068
                w: -0.7071068
    output:
        control_interfaces:
            - control_topic: "/PSM1/servo_jp"
              feedback_topic: "/PSM1/measured_js"
        # output_2_output_reference_rot: # PSM1 BASE TO ECM CAM TIP
        #     quaternion:
        #       x: 0.8434879353433754
        #       y: 0.41486388788676554
        #       z: 0.17562183502837217 
        #       w: 0.2925286798228752

    kinematics:
        robot: "custom"
        module_name: "dvrk_ctr_teleop.RPR_kinematics.RPR_fetal_tool_kinematics_solver"
        class_name: "Arion_Law_tool_Kinematics_Solver"
        config: "../config/mapping/psm1_tool_rpr.yaml"
  - name: "MTMR-PSM2-PeterFrancis"
    input:
        position_scale: 0.5
        type: "follow"
        topic: "/MTMR/measured_cp"
        # input_2_input_reference_rot:
        #     quaternion:
        #         x: 0.9659258 #0
        #         y: 0
        #         z: 0
        #         w: -0.258819 #1
        jaw:
            input_topic: "/MTMR/gripper/measured_js"
            scale: 1
            idx: 11
        hz_divisor: 5
        is_input_device_hold_home_off: True
        servo_cp_topic: "/MTMR/servo_cp"
        servo_cf_topic: "/MTMR/body/servo_cf"
        input_tf_appended_rotation:
            quaternion:
                x: 0
                y: 0
                z: 0.7071068
                w: -0.7071068
    output:
        control_interfaces:
            - control_topic: "/PSM2/servo_jp"
              feedback_topic: "/PSM2/measured_js"
        # output_2_output_reference_rot: # PSM2 BASE TO ECM CAM TIP
        #     quaternion:
        #         x:  .76339054150011531
        #         y:  -0.53537144702185793 #-0.6633578754614509
        #         z: -0.1876093208104334 #-0.31181933480986546
        #         w:  0.30954476356177874 #0.36192662925732555
    kinematics:
        robot: "custom"
        module_name: "dvrk_ctr_teleop.RPR_kinematics.RPR_fetal_tool_kinematics_solver"
        class_name: "Arion_Law_tool_Kinematics_Solver"
        config: "../config/mapping/psm2_tool_rpr.yaml"
clutch_topic: "/console/clutch"
switcher:
  switch_topic: "/console/operator_present"
  disable_list: []
  enable_list: ["MTML-PSM1-PeterFrancis", MTMR-PSM2-PeterFrancis]
enable_at_start: []
