cartesian_controllers:
  - name: "MTML-PSM1-PeterFrancis"
    input:
        position_scale: 0.5
        type: "follow"
        topic: "/MTML/measured_cp"
        input_2_input_reference_rot:
            quaternion:
                x: 0
                y: 0
                z: 0
                w: 1
        jaw:
            input_topic: "/MTML/gripper/measured_js"
            scale: 1
        is_half_hz: True
        is_input_device_hold_home_off: False
        input_device_name: "/MTML/"
    output:
        control_topic: "/PSM1/servo_jp"
        extra_control_topic: "/PSM1/jaw/servo_jp"
        feedback_topic: "/PSM1/measured_js"
        extra_feedback_topic: "/PSM1/jaw/measured_js"
        output_2_output_reference_rot: # PSM1 BASE TO ECM CAM TIP
            quaternion:
                x: 0
                y: 0
                z: 0
                w: 1
    kinematics:
        robot: "custom"
        module_name: "dvrk_ctr_teleop.kinematics.fetal_tool_kinematics_solver"
        class_name: "PeterFrancisToolKinematicsSolver"
  - name: "MTMR-PSM2-PeterFrancis"
    input:
        position_scale: 0.5
        type: "follow"
        topic: "/MTMR/measured_cp"
        input_2_input_reference_rot:
            quaternion:
                x: 0
                y: 0
                z: 0
                w: 1
        jaw:
            input_topic: "/MTMR/gripper/measured_js"
            scale: 1
        is_half_hz: True
        is_input_device_hold_home_off: False
        input_device_name: "/MTMR/"
    output:
        control_topic: "/PSM2/servo_jp"
        extra_control_topic: "/PSM2/jaw/servo_jp"
        feedback_topic: "/PSM2/measured_js"
        extra_feedback_topic: "/PSM2/jaw/measured_js"
        output_2_output_reference_rot: # PSM2 BASE TO ECM CAM TIP
            quaternion:
                x: 0
                y: 0
                z: 0
                w: 1
    kinematics:
        robot: "custom"
        module_name: "dvrk_ctr_teleop.kinematics.fetal_tool_kinematics_solver"
        class_name: "PeterFrancisToolKinematicsSolver"
clutch_topic: "/console/clutch"
