cartesian_controllers:
  - name: "MTMR-PSM2-PeterFrancis"
    input:
        position_scale: 0.5
        type: "follow"
        topic: "/MTMR/measured_cp"
        input_2_input_reference_rot:
            quaternion:
                x: 0.9659258
                y: 0
                z: 0
                w: -0.258819
        jaw:
            input_topic: "/MTMR/gripper/measured_js"
            scale: 1
        hz_divisor: 4
        is_input_device_hold_home_off: True
        input_device_name: "/MTMR/"
    output:
        control_interfaces:
            - control_topic: "/PSM2/servo_jp"
              feedback_topic: "/PSM2/measured_js"
            - control_topic: "/PSM2/jaw/servo_jp"
              feedback_topic: "/PSM2/jaw/measured_js"
        output_2_output_reference_rot: # PSM2 BASE TO ECM CAM TIP
            quaternion:
                x:  1
                y:  0
                z:  0
                w:  0
        is_debug_output_tf: True
    kinematics:
        robot: "custom"
        module_name: "dvrk_ctr_teleop.kinematics.fetal_tool_kinematics_solver"
        class_name: "PeterFrancisToolKinematicsSolver"
clutch_topic: "/console/clutch"
switcher:
  switch_topic: "/console/operator_present"
  disable_list: []
  enable_list: ["MTMR-PSM2-PeterFrancis"]
enable_at_start: []
