cartesian_controllers:
  - name: "MTMR-PSM2-PeterFrancis"
    input:
        position_scale: 0.5
        type: "follow"
        topic: "/MTMR/measured_cp"
        jaw:
            input_topic: "/MTMR/gripper/measured_js"
            scale: 1
        is_half_hz: True
        is_mtm_hold_home_off: True
    output:
        control_topic: "/PSM2/servo_jp"
        extra_control_topic: "/PSM2/jaw/servo_jp"
        feedback_topic: "/PSM2/measured_js"
        extra_feedback_topic: "/PSM2/jaw/measured_js"
        is_debug_output_tf: True
    kinematics:
        robot: "fetal"
        tool:
            type:
clutch_topic: "/console/clutch"
