cartesian_controllers:
  - name: "MTML-PSM1-PeterFrancis"
    input:
        position_scale: 0.5
        type: "follow"
        topic: "/MTML/measured_cp"
        jaw:
            input_topic: "/MTML/gripper/measured_js"
            scale: 1
            idx: 11
        hz_divisor: 4
        is_input_device_hold_home_off: True
        servo_cp_topic: "/MTML/servo_cp"
        servo_cf_topic: "/MTML/body/servo_cf"
        input_tf_appended_rotation:
            quaternion:
                x: 0
                y: 0
                z: 0.7071068
                w: -0.7071068
    output:
        control_interfaces:
            - control_topic: "/PSM1/servo_jp"
              feedback_topic: "/PSM1/measured_js"
        is_debug_output_tf: True
    kinematics:
        robot: "custom"
        module_name: "dvrk_ctr_teleop.RPR_kinematics.RPR_fetal_tool_kinematics_solver"
        class_name: "Arion_Law_tool_Kinematics_Solver"
        config: "../config/mapping/psm1_tool_rpr.yaml"
clutch_topic: "/console/clutch"
switcher:
  switch_topic: "/console/operator_present"
  disable_list: []
  enable_list: ["MTML-PSM1-PeterFrancis"]
enable_at_start: []
