cartesian_controllers:
  - name: "Keyboard-PSM2"
    input:
      type: "increment"
      topic: "/keyboard/twist"
    output:
      control_topic: "/PSM2/servo_jp"
      feedback_topic: "/PSM2/measured_js"
    kinematics:
      robot: "psm"
      tool:
        type: "RTS420007"
joint_controllers:
  - name: "Keyboard-PSM2Jaw"
    input:
      type: "increment"
      topic: "/keyboard/joint_state"
    output:
      control_topic: "/PSM2/jaw/servo_jp"
      feedback_topic: "/PSM2/jaw/measured_js"
clutch_topic: "/console/clutch"
switcher:
  switch_topic: "/toggle/mode"
  disable_list: ["Keyboard-PSM2", Keyboard-PSM2Jaw]
  enable_list: []