default_follower_status: "enabled"                      # can be "enabled" or "disabled"
ros_communication:
  - name: "communication_topics"
    input:
      waypoint_input: "/input/waypoints"
      trajectory_offset_topic: "/trajectory/offset"
      joint_positions_topic: "/PSM2/measured_js"
      jaw_position_topic: "/PSM2/jaw/measured_js"
    output:
      joint_control_topic: "/PSM2/servo_jp"
      jaw_control_topic: "/PSM2/jaw/servo_jp"
      trajectory_status_topic: "/trajectory/status"
      rviz_trajectory_topic: "/plot/trajectory/rviz"
toggle_topic: "/toggle/mode"
motion_generation_parameters:
    general: 
      output_frequency: 50                    # In Hz
      cartesian_interpolating_distance: 0.01  # In meters
      no_of_points_jp: 10                     # Number of points in joint space per cartesian interpolating distance
    jaw:
      interpolating_angle: 0.25               # In degrees
      jaw_angle_open: 30                      # In degrees
      jaw_angle_close: -5                      # In degrees
    default_joint_constraints:
      vlims: [0.3,0.3,0.3,0.3,0.3,0.3]        # Default velocity limits for each joint
      alims: [0.15,0.15,0.15,0.15,0.15,0.15]  # Default acceleration limits for each joint
    kinematics:
      tool: "RTS420007"
cutting_parameters:                           # These come into play only if you are using a scissor
    cutting_cartesian_velocity: 0.002
    max_open: 40                              # Maximum jaw open angle during cutting (in degrees)
    max_close: 0                              # Maximum jaw closing angle during cutting (in degrees)
    distance_close_open: 0.0015               # Distance traveled (m) when the jaw closes/opens
experiment_name: "circle20.txt"