cartesian_controllers:
  - name: "Keyboard-PSM1"
    input:
      type: "increment"
      topic: "/keyboard/twist"
    output:
      control_topic: "/PSM1/servo_jp"
      feedback_topic: "/PSM1/measured_js"
    kinematics:
      robot: "psm"
      tool:
        type: "LND400006"
joint_controllers:
  - name: "Keyboard-PSM1Jaw"
    input:
      type: "increment"
      topic: "/keyboard/joint_state"
    output:
      control_topic: "/PSM1/jaw/servo_jp"
      feedback_topic: "/PSM1/jaw/measured_js"
