cartesian_controllers:
  - name: "Keyboard-PSM1"
    input:
      type: "increment"
      topic: "/keyboard/twist"
    output:
      control_topic: "/PSM1/servo_jp"
      feedback_topic: "/PSM1/measured_js"
      output_ref_to_input_rot:
        lookup_tf:
          base_tf: "base_link"
          camera_tf: "camera_fov_frame"
    kinematics:
      robot: "psm"
      tool:
        type: "LND400006"
