cartesian_controllers:
  - name: "MTMR-PSM2"
    input:
      type: "follow"
      topic: "/servo_cp_follow"
    output:
      control_topic: "/PSM2/servo_jp"
      feedback_topic: "/PSM2/measured_js"
      position_scale: 0.3
    kinematics:
      robot: "psm"
      tool:
        type: "LND400006"
# joint_controllers:
#   - name: "MTMR-PSM2Jaw"
#     input:
#       type: "follow"
#       topic: "/MTMR/gripper/measured_js"
#     output:
#       control_topic: "/PSM2/jaw/servo_jp"
#       feedback_topic: "/PSM2/jaw/measured_js"
clutch_topic: "/console/clutch"
