cartesian_controllers:
  - name: "Keyboard-PSM2_PeterFrancis"
    input:
      type: "increment"
      topic: "/keyboard/twist"
    output:
      control_topic: "/PSM2/servo_jp"
      feedback_topic: "/PSM2/measured_js"
    kinematics:
      robot: "fetal"
      tool:
        type: 
clutch_topic: "/console/clutch"
