cartesian_controllers:
  - name: "Keyboard-PSM2_PeterFrancis"
    input:
      type: "increment"
      topic: "/keyboard/twist"
    output:
      control_topic: "/PSM2/servo_jp"
      feedback_topic: "/PSM2/measured_js"
    kinematics:
      robot: "fetal"
      tool:
        type: "LND400006"
joint_controllers:
  - name: "Keyboard-PSM2Jaw"
    input:
      type: "increment"
      topic: "/keyboard/joint_state"
    output:
      control_topic: "/PSM2/jaw/servo_jp"
      feedback_topic: "/PSM2/jaw/measured_js"
clutch_topic: "/console/clutch"
