cartesian_controllers:
  - name: "Keyboard-PSM1_PeterFrancis"
    input:
      type: "increment"
      topic: "/keyboard/twist"
    output:
      control_topic: "/PSM1/servo_jp"
      feedback_topic: "/PSM1/measured_js"
    kinematics:
      robot: "fetal"
      tool:
        type: 

clutch_topic: "/console/clutch"
