cartesian_controllers:
  - name: "MTMR-PSM2_PeterFrancis"
    input:
      position_scale: 0.5
      type: "follow"
      topic: "/MTMR/measured_cp"
      jaw:
        input_topic: "/MTMR/gripper/measured_js"
        scale: 1
    output:
      control_topic: "/PSM2/servo_jp"
      feedback_topic: "/PSM2/measured_js"
    kinematics:
      robot: "fetal"
      tool:
        type: 
clutch_topic: "/console/clutch"
