// Generated by gencpp from file dvrk_planning_msgs/ComputeIK.msg
// DO NOT EDIT!


#ifndef DVRK_PLANNING_MSGS_MESSAGE_COMPUTEIK_H
#define DVRK_PLANNING_MSGS_MESSAGE_COMPUTEIK_H

#include <ros/service_traits.h>


#include <dvrk_planning_msgs/ComputeIKRequest.h>
#include <dvrk_planning_msgs/ComputeIKResponse.h>


namespace dvrk_planning_msgs
{

struct ComputeIK
{

typedef ComputeIKRequest Request;
typedef ComputeIKResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ComputeIK
} // namespace dvrk_planning_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::dvrk_planning_msgs::ComputeIK > {
  static const char* value()
  {
    return "ae38b9864e967b724fbb0102d7f44916";
  }

  static const char* value(const ::dvrk_planning_msgs::ComputeIK&) { return value(); }
};

template<>
struct DataType< ::dvrk_planning_msgs::ComputeIK > {
  static const char* value()
  {
    return "dvrk_planning_msgs/ComputeIK";
  }

  static const char* value(const ::dvrk_planning_msgs::ComputeIK&) { return value(); }
};


// service_traits::MD5Sum< ::dvrk_planning_msgs::ComputeIKRequest> should match
// service_traits::MD5Sum< ::dvrk_planning_msgs::ComputeIK >
template<>
struct MD5Sum< ::dvrk_planning_msgs::ComputeIKRequest>
{
  static const char* value()
  {
    return MD5Sum< ::dvrk_planning_msgs::ComputeIK >::value();
  }
  static const char* value(const ::dvrk_planning_msgs::ComputeIKRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::dvrk_planning_msgs::ComputeIKRequest> should match
// service_traits::DataType< ::dvrk_planning_msgs::ComputeIK >
template<>
struct DataType< ::dvrk_planning_msgs::ComputeIKRequest>
{
  static const char* value()
  {
    return DataType< ::dvrk_planning_msgs::ComputeIK >::value();
  }
  static const char* value(const ::dvrk_planning_msgs::ComputeIKRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::dvrk_planning_msgs::ComputeIKResponse> should match
// service_traits::MD5Sum< ::dvrk_planning_msgs::ComputeIK >
template<>
struct MD5Sum< ::dvrk_planning_msgs::ComputeIKResponse>
{
  static const char* value()
  {
    return MD5Sum< ::dvrk_planning_msgs::ComputeIK >::value();
  }
  static const char* value(const ::dvrk_planning_msgs::ComputeIKResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::dvrk_planning_msgs::ComputeIKResponse> should match
// service_traits::DataType< ::dvrk_planning_msgs::ComputeIK >
template<>
struct DataType< ::dvrk_planning_msgs::ComputeIKResponse>
{
  static const char* value()
  {
    return DataType< ::dvrk_planning_msgs::ComputeIK >::value();
  }
  static const char* value(const ::dvrk_planning_msgs::ComputeIKResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DVRK_PLANNING_MSGS_MESSAGE_COMPUTEIK_H
