// Generated by gencpp from file dvrk_planning_msgs/ComputeIKRequest.msg
// DO NOT EDIT!


#ifndef DVRK_PLANNING_MSGS_MESSAGE_COMPUTEIKREQUEST_H
#define DVRK_PLANNING_MSGS_MESSAGE_COMPUTEIKREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/TransformStamped.h>

namespace dvrk_planning_msgs
{
template <class ContainerAllocator>
struct ComputeIKRequest_
{
  typedef ComputeIKRequest_<ContainerAllocator> Type;

  ComputeIKRequest_()
    : tf_stamped()  {
    }
  ComputeIKRequest_(const ContainerAllocator& _alloc)
    : tf_stamped(_alloc)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::TransformStamped_<ContainerAllocator>  _tf_stamped_type;
  _tf_stamped_type tf_stamped;





  typedef boost::shared_ptr< ::dvrk_planning_msgs::ComputeIKRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::dvrk_planning_msgs::ComputeIKRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ComputeIKRequest_

typedef ::dvrk_planning_msgs::ComputeIKRequest_<std::allocator<void> > ComputeIKRequest;

typedef boost::shared_ptr< ::dvrk_planning_msgs::ComputeIKRequest > ComputeIKRequestPtr;
typedef boost::shared_ptr< ::dvrk_planning_msgs::ComputeIKRequest const> ComputeIKRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::dvrk_planning_msgs::ComputeIKRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::dvrk_planning_msgs::ComputeIKRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::dvrk_planning_msgs::ComputeIKRequest_<ContainerAllocator1> & lhs, const ::dvrk_planning_msgs::ComputeIKRequest_<ContainerAllocator2> & rhs)
{
  return lhs.tf_stamped == rhs.tf_stamped;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::dvrk_planning_msgs::ComputeIKRequest_<ContainerAllocator1> & lhs, const ::dvrk_planning_msgs::ComputeIKRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace dvrk_planning_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::dvrk_planning_msgs::ComputeIKRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dvrk_planning_msgs::ComputeIKRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dvrk_planning_msgs::ComputeIKRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dvrk_planning_msgs::ComputeIKRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dvrk_planning_msgs::ComputeIKRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dvrk_planning_msgs::ComputeIKRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::dvrk_planning_msgs::ComputeIKRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4da406b78dbcfa9fb31ac9953182c50a";
  }

  static const char* value(const ::dvrk_planning_msgs::ComputeIKRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4da406b78dbcfa9fULL;
  static const uint64_t static_value2 = 0xb31ac9953182c50aULL;
};

template<class ContainerAllocator>
struct DataType< ::dvrk_planning_msgs::ComputeIKRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dvrk_planning_msgs/ComputeIKRequest";
  }

  static const char* value(const ::dvrk_planning_msgs::ComputeIKRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::dvrk_planning_msgs::ComputeIKRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/TransformStamped tf_stamped\n"
"\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/TransformStamped\n"
"# This expresses a transform from coordinate frame header.frame_id\n"
"# to the coordinate frame child_frame_id\n"
"#\n"
"# This message is mostly used by the \n"
"# <a href=\"http://wiki.ros.org/tf\">tf</a> package. \n"
"# See its documentation for more information.\n"
"\n"
"Header header\n"
"string child_frame_id # the frame id of the child frame\n"
"Transform transform\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Transform\n"
"# This represents the transform between two coordinate frames in free space.\n"
"\n"
"Vector3 translation\n"
"Quaternion rotation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::dvrk_planning_msgs::ComputeIKRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::dvrk_planning_msgs::ComputeIKRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.tf_stamped);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ComputeIKRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::dvrk_planning_msgs::ComputeIKRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::dvrk_planning_msgs::ComputeIKRequest_<ContainerAllocator>& v)
  {
    s << indent << "tf_stamped: ";
    s << std::endl;
    Printer< ::geometry_msgs::TransformStamped_<ContainerAllocator> >::stream(s, indent + "  ", v.tf_stamped);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DVRK_PLANNING_MSGS_MESSAGE_COMPUTEIKREQUEST_H
