// Generated by gencpp from file dvrk_planning_msgs/Waypoints.msg
// DO NOT EDIT!


#ifndef DVRK_PLANNING_MSGS_MESSAGE_WAYPOINTS_H
#define DVRK_PLANNING_MSGS_MESSAGE_WAYPOINTS_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <geometry_msgs/Transform.h>

namespace dvrk_planning_msgs
{
template <class ContainerAllocator>
struct Waypoints_
{
  typedef Waypoints_<ContainerAllocator> Type;

  Waypoints_()
    : header()
    , trajectory_name()
    , instruction_mode()
    , jaw_instruction()
    , waypoints()  {
    }
  Waypoints_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , trajectory_name(_alloc)
    , instruction_mode(_alloc)
    , jaw_instruction(_alloc)
    , waypoints(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _trajectory_name_type;
  _trajectory_name_type trajectory_name;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _instruction_mode_type;
  _instruction_mode_type instruction_mode;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _jaw_instruction_type;
  _jaw_instruction_type jaw_instruction;

   typedef std::vector< ::geometry_msgs::Transform_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::geometry_msgs::Transform_<ContainerAllocator> >> _waypoints_type;
  _waypoints_type waypoints;





  typedef boost::shared_ptr< ::dvrk_planning_msgs::Waypoints_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::dvrk_planning_msgs::Waypoints_<ContainerAllocator> const> ConstPtr;

}; // struct Waypoints_

typedef ::dvrk_planning_msgs::Waypoints_<std::allocator<void> > Waypoints;

typedef boost::shared_ptr< ::dvrk_planning_msgs::Waypoints > WaypointsPtr;
typedef boost::shared_ptr< ::dvrk_planning_msgs::Waypoints const> WaypointsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::dvrk_planning_msgs::Waypoints_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::dvrk_planning_msgs::Waypoints_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::dvrk_planning_msgs::Waypoints_<ContainerAllocator1> & lhs, const ::dvrk_planning_msgs::Waypoints_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.trajectory_name == rhs.trajectory_name &&
    lhs.instruction_mode == rhs.instruction_mode &&
    lhs.jaw_instruction == rhs.jaw_instruction &&
    lhs.waypoints == rhs.waypoints;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::dvrk_planning_msgs::Waypoints_<ContainerAllocator1> & lhs, const ::dvrk_planning_msgs::Waypoints_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace dvrk_planning_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::dvrk_planning_msgs::Waypoints_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dvrk_planning_msgs::Waypoints_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dvrk_planning_msgs::Waypoints_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dvrk_planning_msgs::Waypoints_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dvrk_planning_msgs::Waypoints_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dvrk_planning_msgs::Waypoints_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::dvrk_planning_msgs::Waypoints_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d73f1821b5528b13bb35cf8d880f322a";
  }

  static const char* value(const ::dvrk_planning_msgs::Waypoints_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd73f1821b5528b13ULL;
  static const uint64_t static_value2 = 0xbb35cf8d880f322aULL;
};

template<class ContainerAllocator>
struct DataType< ::dvrk_planning_msgs::Waypoints_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dvrk_planning_msgs/Waypoints";
  }

  static const char* value(const ::dvrk_planning_msgs::Waypoints_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::dvrk_planning_msgs::Waypoints_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"string trajectory_name\n"
"string instruction_mode  \n"
"string jaw_instruction               \n"
"geometry_msgs/Transform[] waypoints\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Transform\n"
"# This represents the transform between two coordinate frames in free space.\n"
"\n"
"Vector3 translation\n"
"Quaternion rotation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::dvrk_planning_msgs::Waypoints_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::dvrk_planning_msgs::Waypoints_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.trajectory_name);
      stream.next(m.instruction_mode);
      stream.next(m.jaw_instruction);
      stream.next(m.waypoints);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Waypoints_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::dvrk_planning_msgs::Waypoints_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::dvrk_planning_msgs::Waypoints_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "trajectory_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.trajectory_name);
    s << indent << "instruction_mode: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.instruction_mode);
    s << indent << "jaw_instruction: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.jaw_instruction);
    s << indent << "waypoints[]" << std::endl;
    for (size_t i = 0; i < v.waypoints.size(); ++i)
    {
      s << indent << "  waypoints[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::geometry_msgs::Transform_<ContainerAllocator> >::stream(s, indent + "    ", v.waypoints[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // DVRK_PLANNING_MSGS_MESSAGE_WAYPOINTS_H
