wrist_bending_compensation: 0.9
wrist_length: 0.0015 #CHANGE THIS 
wrist_pitch_joint_limits: [0, 1.57]
small_capstan_diameter: 5.08 #mm
max_EE_pinch_angle_deg: 45 #deg (jaw to midline)
min_EE_pinch_angle_deg: -30 #deg (jaw to midline)
gripper_scissor_linkage_length: 1.4 #mm
simulation: False
scale: 10 #Scaling factor for tool insertion 