wrist_bending_compensation: 0.2
wrist_length: 0.0015 #CHANGE THIS 
wrist_pitch_joint_limits: [0.0, 1.57]
wrist_outer_roll_joint_limits: [-1.57,1.57]
wrist_inner_roll_joint_limits: [-3.14,3.14]
small_capstan_diameter: 5.08 #mm
max_EE_pinch_angle_deg: 45 #deg (jaw to midline)
min_EE_pinch_angle_deg: -40 #deg (jaw to midline)
gripper_scissor_linkage_length: 1.6 #mm
min_deg_limit: 5 #proximity to singularity
simulation: False
scale: 10 #Scaling factor for tool insertion 